CREATE DATABASE IF NOT EXISTS MARKETING_INSIGHTS;
USE MARKETING_INSIGHTS;

CREATE TABLE IF NOT EXISTS customers (
    customer_id INT PRIMARY KEY,
    gender VARCHAR(1),
    located VARCHAR(30),
    tenure_months INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS discountCoupon (
    coupon_id INT PRIMARY KEY AUTO_INCREMENT, 
    product_category VARCHAR(30),
    month_code VARCHAR(5),
    coupon_code VARCHAR(10),
    discount_pct INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS marketingSpend (
    spend_id INT PRIMARY KEY AUTO_INCREMENT, 
    date_spend DATE,
    offline_spend INT,
    online_spend DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS onlineSales (
    customer_id INT,
    transaction_id INT, 
    transaction_date DATE,
    product_sku VARCHAR(30),
    product_description VARCHAR(150),
    product_category VARCHAR(30),
    quantity INT,
    average_price DECIMAL(5,2),
    delivery_charges DECIMAL(5,2), 
    coupon_status VARCHAR(10),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

